function createfigure(data1)
%CREATEFIGURE(DATA1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 16-Oct-2018 14:17:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'Parent',axes1,'BinMethod','auto');

% Create xlabel
xlabel({'x values'});

% Create title
title({'Histogram'});

% Create ylabel
ylabel({'y values'});

box(axes1,'on');
